"""add historical sponsorship evidence

Revision ID: e032f5914315
Revises: ace28f3f08d2
Create Date: 2026-08-12 22:58:17.779848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e032f5914315'
down_revision: Union[str, Sequence[str], None] = 'ace28f3f08d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_sponsorship_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('historical_support', sa.Boolean(), nullable=False),
    sa.Column('employer_match_type', sa.String(length=100), nullable=True),
    sa.Column('occupation_match_type', sa.String(length=100), nullable=True),
    sa.Column('matched_dol_employer', sa.String(length=500), nullable=True),
    sa.Column('matched_dol_job_title', sa.String(length=500), nullable=True),
    sa.Column('matched_soc_code', sa.String(length=20), nullable=True),
    sa.Column('matched_soc_title', sa.String(length=500), nullable=True),
    sa.Column('certified_lca_cases', sa.Integer(), nullable=False),
    sa.Column('worker_positions', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('matching_version', sa.String(length=50), nullable=False),
    sa.Column('evidence_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'matching_version', name='uq_job_historical_matching_version')
    )
    op.create_index(op.f('ix_historical_sponsorship_evidence_historical_support'), 'historical_sponsorship_evidence', ['historical_support'], unique=False)
    op.create_index(op.f('ix_historical_sponsorship_evidence_job_id'), 'historical_sponsorship_evidence', ['job_id'], unique=False)
    op.create_index(op.f('ix_historical_sponsorship_evidence_requires_human_review'), 'historical_sponsorship_evidence', ['requires_human_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_sponsorship_evidence_requires_human_review'), table_name='historical_sponsorship_evidence')
    op.drop_index(op.f('ix_historical_sponsorship_evidence_job_id'), table_name='historical_sponsorship_evidence')
    op.drop_index(op.f('ix_historical_sponsorship_evidence_historical_support'), table_name='historical_sponsorship_evidence')
    op.drop_table('historical_sponsorship_evidence')
    # ### end Alembic commands ###
